name: CICD workflow for Snake Game application

on:
  workflow_dispatch:

  push:
    branches:
      - main


jobs:
  build_code:
    runs-on: ['self-hosted', 'Linux', 'X64']



    steps:
   
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
